# Generated by Django 5.2 on 2025-05-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("uasg", models.CharField(max_length=10, unique=True)),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("endereco", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="uasg",
        ),
        migrations.AddField(
            model_name="dashboard",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.hospital",
            ),
        ),
    ]
