# Generated by Django 5.2 on 2025-05-31 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_hospital_remove_dashboard_uasg_dashboard_hospital"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("STEC", "STEC"), ("SEC", "SEC"), ("CEO", "CEO")],
                        max_length=10,
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("ENGENHEIRO", "Engenheiro Clínico"),
                            ("ASSISTENTE", "Assistente Administrativo"),
                            ("ANALISTA", "Analista Administrativo"),
                            ("DIRETOR", "Diretor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.hospital",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
