# Generated by Django 5.2 on 2025-05-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_perfilusuario_delete_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
