# Generated by Django 5.2 on 2025-06-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_perfilusuario_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="nome_completo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
