# Generated by Django 5.2 on 2025-06-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_perfilusuario_nome_completo"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="hospital",
            name="estado",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="nome_completo",
            field=models.CharField(default="Nome Padrão", max_length=255),
            preserve_default=False,
        ),
    ]
