# Generated by Django 5.2 on 2025-05-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DispositivoMedicoAnvisa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_registro_cadastro", models.CharField(max_length=50)),
                (
                    "numero_processo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nome_tecnico",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "classe_risco",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nome_comercial",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cnpj_detentor_registro",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "detentor_registro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nome_fabricante",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nome_pais_fabricante",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("data_publicacao_registro", models.DateField(blank=True, null=True)),
                ("validade_registro", models.DateField(blank=True, null=True)),
                ("data_atualizacao", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
