# Generated by Django 5.2 on 2025-06-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos_medicos_anvisa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispositivomedicoanvisa",
            name="validade_registro",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
