# Generated by Django 5.2 on 2025-04-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AtaRegistroPreco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_ata", models.CharField(max_length=50, unique=True)),
                ("edital", models.CharField(max_length=100)),
                ("uasg", models.CharField(max_length=20)),
                ("hospital", models.CharField(max_length=255)),
                ("numero_sei", models.CharField(max_length=50)),
                ("vigencia_inicio", models.DateField()),
                ("vigencia_fim", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ItemDaAta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_item", models.CharField(max_length=255)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("garantia_meses", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=15)),
                ("empresa", models.CharField(max_length=255)),
                ("item_no_srp", models.CharField(max_length=50)),
                (
                    "ata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="gestaodeatas.ataregistropreco",
                    ),
                ),
            ],
        ),
    ]
