# Generated by Django 5.2 on 2025-05-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaodeatas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemdaata",
            name="catmat_sugerido",
            field=models.CharField(
                blank=True,
                help_text="Código CATMAT sugerido (opcional)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemdaata",
            name="corrigido_por",
            field=models.CharField(
                blank=True,
                help_text="Nome de quem sugeriu a correção",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemdaata",
            name="descricao_corrigida",
            field=models.TextField(
                blank=True,
                help_text="Descrição técnica padronizada (opcional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="itemdaata",
            name="tipo_item",
            field=models.CharField(
                choices=[("bem", "Bem"), ("servico", "Serviço")],
                default="bem",
                help_text="Classifique o item como Bem ou Serviço",
                max_length=10,
            ),
        ),
    ]
