# Generated by Django 5.2 on 2025-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestaodeatas",
            "0002_itemdaata_catmat_sugerido_itemdaata_corrigido_por_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ataregistropreco",
            name="edital",
            field=models.CharField(max_length=100, verbose_name="Edital"),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="hospital",
            field=models.CharField(max_length=255, verbose_name="Hospital"),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="numero_ata",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Número da Ata"
            ),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="numero_sei",
            field=models.CharField(max_length=50, verbose_name="Número SEI"),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="uasg",
            field=models.CharField(max_length=20, verbose_name="UASG"),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="vigencia_fim",
            field=models.DateField(verbose_name="Vigência Final"),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="vigencia_inicio",
            field=models.DateField(verbose_name="Vigência Inicial"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="catmat_sugerido",
            field=models.CharField(
                blank=True,
                help_text="Código CATMAT sugerido (opcional)",
                max_length=20,
                null=True,
                verbose_name="CATMAT Sugerido",
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="corrigido_por",
            field=models.CharField(
                blank=True,
                help_text="Nome de quem sugeriu a correção",
                max_length=255,
                null=True,
                verbose_name="Corrigido por",
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="descricao_corrigida",
            field=models.TextField(
                blank=True,
                help_text="Descrição técnica padronizada (opcional)",
                null=True,
                verbose_name="Descrição Corrigida",
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="empresa",
            field=models.CharField(max_length=255, verbose_name="Empresa"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="garantia_meses",
            field=models.PositiveIntegerField(verbose_name="Garantia (meses)"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="item_no_srp",
            field=models.CharField(max_length=50, verbose_name="Item no SRP"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="marca",
            field=models.CharField(max_length=100, verbose_name="Marca"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="modelo",
            field=models.CharField(max_length=100, verbose_name="Modelo"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="nome_item",
            field=models.CharField(max_length=255, verbose_name="Nome do Item"),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="tipo_item",
            field=models.CharField(
                choices=[("bem", "Bem"), ("servico", "Serviço")],
                default="bem",
                help_text="Classifique o item como Bem ou Serviço",
                max_length=10,
                verbose_name="Tipo de Item",
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Valor (R$)"
            ),
        ),
    ]
