# Generated by Django 5.2 on 2025-05-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaodeatas", "0004_ataregistropreco_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ataregistropreco",
            name="status",
            field=models.CharField(
                choices=[
                    ("Homologada", "Homologada"),
                    ("Pendente", "Pendente"),
                    ("Cancelada", "Cancelada"),
                    ("Em Andamento", "Em Andamento"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
