# Generated by Django 5.2 on 2025-05-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestaodeatas", "0005_alter_ataregistropreco_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ataregistropreco",
            name="data_assinatura",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Assinatura"
            ),
        ),
        migrations.AddField(
            model_name="ataregistropreco",
            name="data_atualizacao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AddField(
            model_name="ataregistropreco",
            name="data_inclusao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Inclusão"
            ),
        ),
        migrations.AddField(
            model_name="ataregistropreco",
            name="data_publicacao_pncp",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Publicação PNCP"
            ),
        ),
        migrations.AddField(
            model_name="ataregistropreco",
            name="nome_orgao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nome do Órgão"
            ),
        ),
        migrations.AddField(
            model_name="ataregistropreco",
            name="objeto_contratacao",
            field=models.TextField(
                blank=True, null=True, verbose_name="Objeto da Contratação"
            ),
        ),
        migrations.AddField(
            model_name="ataregistropreco",
            name="valor_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
                verbose_name="Valor Total (R$)",
            ),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="edital",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Edital"
            ),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="numero_sei",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número SEI"
            ),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="status",
            field=models.CharField(
                choices=[
                    ("Homologada", "Homologada"),
                    ("Cancelada", "Cancelada"),
                    ("Pendente", "Pendente"),
                ],
                default="Pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="vigencia_fim",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vigência Final"
            ),
        ),
        migrations.AlterField(
            model_name="ataregistropreco",
            name="vigencia_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vigência Inicial"
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="catmat_sugerido",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="CATMAT Sugerido"
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="corrigido_por",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Corrigido por"
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="descricao_corrigida",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição Corrigida"
            ),
        ),
        migrations.AlterField(
            model_name="itemdaata",
            name="tipo_item",
            field=models.CharField(
                choices=[("bem", "Bem"), ("servico", "Serviço")],
                default="bem",
                max_length=10,
                verbose_name="Tipo de Item",
            ),
        ),
    ]
